server:
  port: 8989
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: dev
    password: jyotheesh
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true